import { createClientFromRequest } from "npm:@base44/sdk@0.8.44";
import { secrets } from "base44:runtime";
import { json, normalizePhone, phoneHash, encryptPhone, decryptPhone, sha256, randomToken, otpCode, now } from "../../shared/security.ts";
import { sendSMS } from "../../shared/telnyx.ts";
import { moderate, CATEGORIES, POLICY_VERSION } from "../../shared/moderation.ts";

async function requireUser(base44:any){ const user=await base44.auth.me(); if(!user) throw Object.assign(new Error("Unauthorized"),{status:401}); return user; }
async function profile(base44:any,userId:string){ const rows=await base44.asServiceRole.entities.Profile.filter({user_id:userId},"-created_date",1); return rows[0]||null; }
async function identity(base44:any,userId:string){ const rows=await base44.asServiceRole.entities.RecipientIdentity.filter({user_id:userId},"-created_date",1); return rows[0]||null; }
async function chargeCredit(base44:any,p:any,messageId:string){
  if((p.free_credit_remaining||0)>0){ await base44.asServiceRole.entities.Profile.update(p.id,{free_credit_remaining:p.free_credit_remaining-1}); await base44.asServiceRole.entities.CreditTransaction.create({user_id:p.user_id,type:"MESSAGE_DEBIT",quantity:-1,balance_after:(p.free_credit_remaining-1)+(p.purchased_credits||0),message_id:messageId}); return "FREE"; }
  if((p.purchased_credits||0)>0){ await base44.asServiceRole.entities.Profile.update(p.id,{purchased_credits:p.purchased_credits-1}); await base44.asServiceRole.entities.CreditTransaction.create({user_id:p.user_id,type:"MESSAGE_DEBIT",quantity:-1,balance_after:(p.free_credit_remaining||0)+p.purchased_credits-1,message_id:messageId}); return "PURCHASED"; }
  return "NONE";
}
async function refundCredit(base44:any,p:any,source:string,messageId:string){ if(source==="FREE") await base44.asServiceRole.entities.Profile.update(p.id,{free_credit_remaining:(p.free_credit_remaining||0)+1}); if(source==="PURCHASED") await base44.asServiceRole.entities.Profile.update(p.id,{purchased_credits:(p.purchased_credits||0)+1}); if(source!=="NONE") await base44.asServiceRole.entities.CreditTransaction.create({user_id:p.user_id,type:"REFUND",quantity:1,balance_after:(p.free_credit_remaining||0)+(p.purchased_credits||0)+1,message_id:messageId}); }

export default async function(req:Request){
  const base44=createClientFromRequest(req);
  try{
    const user=await requireUser(base44); const body=await req.json(); const action=String(body?.action||"");
    if(action==="account"){
      const p=await profile(base44,user.id); return json({user:{id:user.id,email:user.email},profile:p?{nickname:p.nickname,phone_last4:p.phone_last4,phone_verified:p.phone_verified,sms_consent_status:p.sms_consent_status,free_credit_remaining:p.free_credit_remaining,purchased_credits:p.purchased_credits,account_status:p.account_status,trust_level:p.trust_level}:null});
    }
    if(action==="request_phone_otp"){
      const phone=normalizePhone(body.phone); const h=await phoneHash(phone); const existing=await base44.asServiceRole.entities.RecipientIdentity.filter({phone_hash:h},"-created_date",1); if(existing.length&&existing[0].user_id!==user.id)return json({error:"Phone number is already registered"},409);
      const recent=await base44.asServiceRole.entities.PhoneVerification.filter({user_id:user.id,status:"PENDING"},"-created_date",10); const cutoff=Date.now()-10*60*1000; if(recent.filter((r:any)=>new Date(r.created_date).getTime()>cutoff).length>=3)return json({error:"Too many verification requests. Try later."},429);
      const code=otpCode(); const enc=await encryptPhone(phone); const code_hash=await sha256(`${code}:${secrets.get("PHONE_HASH_PEPPER")}`); const expires=new Date(Date.now()+10*60*1000).toISOString();
      await base44.asServiceRole.entities.PhoneVerification.create({user_id:user.id,phone_hash:h,phone_ciphertext:enc.ciphertext,phone_iv:enc.iv,code_hash,expires_at:expires,attempts:0,status:"PENDING"}); await sendSMS(phone,`Private Feedback verification code: ${code}. It expires in 10 minutes.`); return json({ok:true,expires_at:expires});
    }
    if(action==="verify_phone_otp"){
      const rows=await base44.asServiceRole.entities.PhoneVerification.filter({user_id:user.id,status:"PENDING"},"-created_date",1); if(!rows.length)return json({error:"No pending verification"},404); const v=rows[0]; if(new Date(v.expires_at).getTime()<Date.now()){await base44.asServiceRole.entities.PhoneVerification.update(v.id,{status:"EXPIRED"});return json({error:"Code expired"},410);} if(v.attempts>=5){await base44.asServiceRole.entities.PhoneVerification.update(v.id,{status:"LOCKED"});return json({error:"Verification locked"},423);} const provided=await sha256(`${String(body.code||"")}:${secrets.get("PHONE_HASH_PEPPER")}`); if(provided!==v.code_hash){await base44.asServiceRole.entities.PhoneVerification.update(v.id,{attempts:v.attempts+1});return json({error:"Invalid code"},400);} const phone=await decryptPhone(v.phone_ciphertext,v.phone_iv); const existing=await profile(base44,user.id); let p:any; if(existing){p=await base44.asServiceRole.entities.Profile.update(existing.id,{nickname:String(body.nickname||existing.nickname).slice(0,50),phone_hash:v.phone_hash,phone_last4:phone.slice(-4),phone_verified:true,sms_consent_status:body.sms_consent?"ACTIVE":"NONE",sms_consent_at:body.sms_consent?now():existing.sms_consent_at,sms_consent_version:"2026-08-30-v1",account_status:"ACTIVE",trust_level:"VERIFIED"});}else{p=await base44.asServiceRole.entities.Profile.create({user_id:user.id,nickname:String(body.nickname||"User").slice(0,50),phone_hash:v.phone_hash,phone_last4:phone.slice(-4),phone_verified:true,sms_consent_status:body.sms_consent?"ACTIVE":"NONE",sms_consent_at:body.sms_consent?now():"",sms_consent_version:"2026-08-30-v1",free_credit_remaining:1,purchased_credits:0,account_status:"ACTIVE",risk_score:0,trust_level:"VERIFIED"}); await base44.asServiceRole.entities.CreditTransaction.create({user_id:user.id,type:"FREE_GRANT",quantity:1,balance_after:1});}
      const idRows=await base44.asServiceRole.entities.RecipientIdentity.filter({user_id:user.id},"-created_date",1); const idData={user_id:user.id,phone_hash:v.phone_hash,phone_ciphertext:v.phone_ciphertext,phone_iv:v.phone_iv,phone_last4:phone.slice(-4),sms_consent_status:body.sms_consent?"ACTIVE":"NONE",consent_source:"REGISTRATION",consent_timestamp:body.sms_consent?now():"",consent_version:"2026-08-30-v1",messages_last_24h:0}; if(idRows.length)await base44.asServiceRole.entities.RecipientIdentity.update(idRows[0].id,idData);else await base44.asServiceRole.entities.RecipientIdentity.create(idData); await base44.asServiceRole.entities.PhoneVerification.update(v.id,{status:"VERIFIED"}); return json({ok:true,profile:{nickname:p.nickname,phone_last4:p.phone_last4,sms_consent_status:p.sms_consent_status}});
    }
    if(action==="lookup_recipient"){
      const h=await phoneHash(body.phone); const rows=await base44.asServiceRole.entities.RecipientIdentity.filter({phone_hash:h},"-created_date",1); if(!rows.length)return json({eligible:false,reason:"NOT_REGISTERED"}); const r=rows[0]; const rp=await profile(base44,r.user_id); return json({eligible:!!(rp&&rp.account_status==="ACTIVE"&&r.sms_consent_status==="ACTIVE"),reason:r.sms_consent_status==="ACTIVE"?null:"SMS_NOT_ENABLED"});
    }
    if(action==="preview_feedback"){
      const p=await profile(base44,user.id); if(!p||p.account_status!=="ACTIVE")return json({error:"Active verified profile required"},403); const result=await moderate(base44,String(body.category),String(body.message||"")); return json({risk_level:result.risk_level,decision:result.decision,refined_text:result.refined_text,reason_codes:result.reason_codes});
    }
    if(action==="send_feedback"){
      const p=await profile(base44,user.id); if(!p||!p.phone_verified||p.account_status!=="ACTIVE")return json({error:"Verified active profile required"},403); const recipientPhone=normalizePhone(body.recipient_phone); const recipientHash=await phoneHash(recipientPhone); const ids=await base44.asServiceRole.entities.RecipientIdentity.filter({phone_hash:recipientHash},"-created_date",1); if(!ids.length)return json({error:"Recipient is not registered",code:"RECIPIENT_NOT_REGISTERED"},409); const ri=ids[0]; if(ri.user_id===user.id)return json({error:"You cannot send feedback to yourself"},400); if(ri.sms_consent_status!=="ACTIVE")return json({error:"Recipient is not accepting SMS feedback",code:"RECIPIENT_SMS_DISABLED"},409); const rp=await profile(base44,ri.user_id); if(!rp||rp.account_status!=="ACTIVE")return json({error:"Recipient unavailable"},409); const blocks=await base44.asServiceRole.entities.RecipientBlock.filter({recipient_user_id:ri.user_id,blocked_sender_user_id:user.id,active:true},"-created_date",1); if(blocks.length)return json({error:"Recipient unavailable for feedback"},409);
      const since=new Date(Date.now()-30*24*60*60*1000).toISOString(); const prior=await base44.asServiceRole.entities.FeedbackMessage.filter({sender_user_id:user.id,recipient_phone_hash:recipientHash},"-created_date",20); if(prior.filter((x:any)=>x.created_date>=since&&!['AI_REJECTED','REFUNDED','FAILED'].includes(x.delivery_status)).length>=2)return json({error:"Feedback limit reached for this recipient"},429);
      const category=String(body.category); if(!CATEGORIES.includes(category as any))return json({error:"Invalid category"},400); const raw=String(body.message||""); const mod=await moderate(base44,category,raw); const feedback=await base44.asServiceRole.entities.FeedbackMessage.create({sender_user_id:user.id,recipient_user_id:ri.user_id,recipient_phone_hash:recipientHash,recipient_name:String(body.recipient_name||"Someone").slice(0,50),category,original_text:raw,refined_text:mod.refined_text,moderation_status:mod.risk_level==="RED"?"AI_REJECTED":mod.risk_level==="ORANGE"?"HUMAN_REVIEW":"APPROVED",moderation_reason:(mod.reason_codes||[]).join(","),risk_level:mod.risk_level,delivery_status:mod.risk_level==="RED"?"FAILED":mod.risk_level==="ORANGE"?"DRAFT":"QUEUED",credit_source:"NONE",credit_cost:0}); await base44.asServiceRole.entities.ModerationDecision.create({feedback_id:feedback.id,model:"Base44 InvokeLLM automatic",policy_version:POLICY_VERSION,classification:mod.classification,risk_level:mod.risk_level,decision:mod.decision,reason_codes:mod.reason_codes||[],removed_claims:mod.removed_claims||[],refined_text:mod.refined_text}); if(mod.risk_level==="RED")return json({ok:false,rejected:true,reason_codes:mod.reason_codes},422); if(mod.risk_level==="ORANGE")return json({ok:true,status:"HUMAN_REVIEW",feedback_id:feedback.id}); const source=await chargeCredit(base44,p,feedback.id); if(source==="NONE"){await base44.asServiceRole.entities.FeedbackMessage.update(feedback.id,{delivery_status:"AWAITING_PAYMENT"});return json({ok:false,payment_required:true,feedback_id:feedback.id},402);} const token=randomToken(); const tokenHash=await sha256(token); const expires=new Date(Date.now()+24*60*60*1000).toISOString(); await base44.asServiceRole.entities.FeedbackAccessToken.create({feedback_id:feedback.id,recipient_user_id:ri.user_id,token_hash:tokenHash,expires_at:expires,status:"ACTIVE"}); const url=`${secrets.get("APP_PUBLIC_URL").replace(/\/$/,"")}/f/${token}`; try{ const sms=await sendSMS(recipientPhone,`Hi ${String(body.recipient_name||"there").slice(0,30)} — you received private AI-moderated feedback. Category: ${category}. View it securely for 24 hours: ${url} Reply STOP to stop SMS notifications.`); await base44.asServiceRole.entities.SMSMessage.create({telnyx_message_id:sms?.id||"",direction:"OUTBOUND",from_number:"***6111",to_number:`***${recipientPhone.slice(-4)}`,body:"[private feedback notification]",message_type:"FEEDBACK_NOTIFICATION",feedback_id:feedback.id,status:"SENT"}); await base44.asServiceRole.entities.FeedbackMessage.update(feedback.id,{delivery_status:"DELIVERED",credit_source:source,credit_cost:1,access_expires_at:expires,delivered_at:now()}); return json({ok:true,feedback_id:feedback.id,status:"DELIVERED",expires_at:expires}); }catch(e){await refundCredit(base44,p,source,feedback.id); await base44.asServiceRole.entities.FeedbackMessage.update(feedback.id,{delivery_status:"FAILED",credit_source:source,credit_cost:1}); throw e; }
    }
    if(action==="open_feedback"){
      const token=String(body.token||""); const h=await sha256(token); const tokens=await base44.asServiceRole.entities.FeedbackAccessToken.filter({token_hash:h,status:"ACTIVE"},"-created_date",1); if(!tokens.length)return json({error:"Invalid or expired link"},404); const t=tokens[0]; if(t.recipient_user_id!==user.id)return json({error:"This link belongs to another account"},403); if(new Date(t.expires_at).getTime()<Date.now()){await base44.asServiceRole.entities.FeedbackAccessToken.update(t.id,{status:"EXPIRED"});return json({error:"Link expired"},410);} const f=await base44.asServiceRole.entities.FeedbackMessage.get(t.feedback_id); if(!f||f.recipient_user_id!==user.id||f.moderation_status!=="APPROVED")return json({error:"Feedback unavailable"},404); if(!t.first_viewed_at)await base44.asServiceRole.entities.FeedbackAccessToken.update(t.id,{first_viewed_at:now()}); if(f.delivery_status==="DELIVERED")await base44.asServiceRole.entities.FeedbackMessage.update(f.id,{delivery_status:"VIEWED",viewed_at:now()}); return json({feedback_id:f.id,category:f.category,refined_text:f.refined_text,expires_at:t.expires_at,disclaimer:"This represents the sender's personal perspective and has not been independently verified by the platform."});
    }
    if(action==="inbox"){
      const rows=await base44.asServiceRole.entities.FeedbackMessage.filter({recipient_user_id:user.id},"-created_date",100); return json({items:rows.filter((f:any)=>f.moderation_status==="APPROVED"&&["DELIVERED","VIEWED","REPLIED","REPORTED"].includes(f.delivery_status)).map((f:any)=>({id:f.id,category:f.category,refined_text:f.refined_text,status:f.delivery_status,delivered_at:f.delivered_at,viewed_at:f.viewed_at}))});
    }
    if(action==="reply"){
      const feedback=await base44.asServiceRole.entities.FeedbackMessage.get(String(body.feedback_id||"")); if(!feedback||feedback.recipient_user_id!==user.id)return json({error:"Not found"},404); let convs=await base44.asServiceRole.entities.Conversation.filter({feedback_id:feedback.id},"-created_date",1); const conv=convs[0]||await base44.asServiceRole.entities.Conversation.create({feedback_id:feedback.id,sender_user_id:feedback.sender_user_id,recipient_user_id:user.id,status:"OPEN",last_activity_at:now()}); if(conv.status!=="OPEN")return json({error:"Conversation unavailable"},409); const mod=await moderate(base44,"Communication",String(body.message||"")); const cm=await base44.asServiceRole.entities.ConversationMessage.create({conversation_id:conv.id,actor_user_id:user.id,actor_role:"RECIPIENT",original_text:String(body.message||""),refined_text:mod.refined_text,moderation_status:mod.risk_level==="RED"?"AI_REJECTED":mod.risk_level==="ORANGE"?"HUMAN_REVIEW":"APPROVED",risk_level:mod.risk_level,delivered_at:mod.risk_level==="GREEN"||mod.risk_level==="YELLOW"?now():""}); if(mod.risk_level==="RED")return json({error:"Reply rejected by moderation"},422); if(mod.risk_level==="ORANGE")return json({ok:true,status:"HUMAN_REVIEW"}); await base44.asServiceRole.entities.Conversation.update(conv.id,{last_activity_at:now()}); await base44.asServiceRole.entities.FeedbackMessage.update(feedback.id,{delivery_status:"REPLIED"}); return json({ok:true,message_id:cm.id,refined_text:mod.refined_text});
    }
    if(action==="report"){
      const feedback=await base44.asServiceRole.entities.FeedbackMessage.get(String(body.feedback_id||"")); if(!feedback||feedback.recipient_user_id!==user.id)return json({error:"Not found"},404); await base44.asServiceRole.entities.AbuseReport.create({reporter_user_id:user.id,feedback_id:feedback.id,reason:String(body.reason||"Other").slice(0,100),details:String(body.details||"").slice(0,1000),status:"OPEN"}); await base44.asServiceRole.entities.FeedbackMessage.update(feedback.id,{delivery_status:"REPORTED"}); return json({ok:true});
    }
    if(action==="block_sender"){
      const feedback=await base44.asServiceRole.entities.FeedbackMessage.get(String(body.feedback_id||"")); if(!feedback||feedback.recipient_user_id!==user.id)return json({error:"Not found"},404); const rows=await base44.asServiceRole.entities.RecipientBlock.filter({recipient_user_id:user.id,blocked_sender_user_id:feedback.sender_user_id},"-created_date",1); if(rows.length)await base44.asServiceRole.entities.RecipientBlock.update(rows[0].id,{active:true,reason:String(body.reason||"Recipient block").slice(0,200)});else await base44.asServiceRole.entities.RecipientBlock.create({recipient_user_id:user.id,blocked_sender_user_id:feedback.sender_user_id,reason:String(body.reason||"Recipient block").slice(0,200),active:true}); await base44.asServiceRole.entities.FeedbackMessage.update(feedback.id,{delivery_status:"BLOCKED"}); return json({ok:true});
    }
    if(action==="update_sms_consent"){
      const status=body.enabled?"ACTIVE":"STOPPED"; const p=await profile(base44,user.id); const ri=await identity(base44,user.id); if(!p||!ri)return json({error:"Verified phone required"},409); await base44.asServiceRole.entities.Profile.update(p.id,{sms_consent_status:status,sms_consent_at:body.enabled?now():p.sms_consent_at}); await base44.asServiceRole.entities.RecipientIdentity.update(ri.id,{sms_consent_status:status,consent_source:"SETTINGS",consent_timestamp:body.enabled?now():ri.consent_timestamp}); return json({ok:true,status});
    }
    if(action==="create_checkout"){
      const p=await profile(base44,user.id); if(!p)return json({error:"Profile required"},409); const product=body.product_type==="PACK_20"?"PACK_20":"SINGLE_MESSAGE"; const unit=product==="PACK_20"?599:100; const credits=product==="PACK_20"?20:1; const params=new URLSearchParams(); params.set("mode","payment"); params.set("success_url",String(body.success_url||secrets.get("APP_PUBLIC_URL"))+"?payment=success"); params.set("cancel_url",String(body.cancel_url||secrets.get("APP_PUBLIC_URL"))+"?payment=cancelled"); params.set("automatic_tax[enabled]","true"); params.set("line_items[0][quantity]","1"); params.set("line_items[0][price_data][currency]","cad"); params.set("line_items[0][price_data][unit_amount]",String(unit)); params.set("line_items[0][price_data][product_data][name]",product==="PACK_20"?"20 Private Feedback Credits":"1 Private Feedback Credit"); params.set("metadata[user_id]",user.id); params.set("metadata[credits]",String(credits)); params.set("metadata[product_type]",product); const res=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secrets.get("STRIPE_SECRET_KEY")}`,"Content-Type":"application/x-www-form-urlencoded"},body:params}); const data=await res.json(); if(!res.ok)return json({error:"Stripe checkout failed",details:data},502); await base44.asServiceRole.entities.Purchase.create({user_id:user.id,product_type:product,subtotal_cents:unit,tax_cents:0,total_cents:unit,currency:"CAD",credits,processor:"STRIPE",processor_payment_id:data.id,status:"PENDING"}); return json({checkout_url:data.url,session_id:data.id});
    }
    return json({error:"Unknown action"},400);
  }catch(e:any){ return json({error:e?.message||"Backend error"},e?.status||500); }
}