// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface AbuseReport {
  reporter_user_id: string;
  feedback_id: string;
  reason: string;
  details?: string;
  status: "OPEN" | "REVIEWING" | "ACTIONED" | "DISMISSED";
  assigned_admin?: string;
}

export interface Conversation {
  feedback_id: string;
  sender_user_id: string;
  recipient_user_id: string;
  status: "OPEN" | "CLOSED" | "BLOCKED";
  last_activity_at?: string;
}

export interface ConversationMessage {
  conversation_id: string;
  actor_user_id: string;
  actor_role: "SENDER" | "RECIPIENT";
  original_text: string;
  refined_text?: string;
  moderation_status: "AI_PROCESSING" | "AI_REJECTED" | "HUMAN_REVIEW" | "APPROVED";
  risk_level: "GREEN" | "YELLOW" | "ORANGE" | "RED";
  delivered_at?: string;
}

export interface CreditTransaction {
  user_id: string;
  type: "FREE_GRANT" | "PURCHASE" | "MESSAGE_DEBIT" | "REFUND" | "ADMIN_ADJUSTMENT";
  quantity: number;
  balance_after: number;
  payment_id?: string;
  message_id?: string;
}

export interface FeedbackAccessToken {
  feedback_id: string;
  recipient_user_id: string;
  token_hash: string;
  expires_at: string;
  status: "ACTIVE" | "EXPIRED" | "REVOKED";
  first_viewed_at?: string;
}

export interface FeedbackMessage {
  sender_user_id: string;
  recipient_user_id?: string;
  recipient_phone_hash: string;
  recipient_name: string;
  category:
    | "Hygiene"
    | "Dating"
    | "Friendship"
    | "Workplace"
    | "Neighbour"
    | "Habit"
    | "Communication"
    | "Appearance/style"
    | "Appreciation"
    | "Apology"
    | "Something difficult to say";
  original_text: string;
  refined_text?: string;
  moderation_status: "DRAFT" | "AI_PROCESSING" | "AI_REJECTED" | "HUMAN_REVIEW" | "APPROVED";
  moderation_reason?: string;
  risk_level: "GREEN" | "YELLOW" | "ORANGE" | "RED";
  delivery_status:
    | "DRAFT"
    | "AWAITING_PAYMENT"
    | "PAYMENT_COMPLETE"
    | "AWAITING_RECIPIENT_OPT_IN"
    | "QUEUED"
    | "SENDING"
    | "DELIVERED"
    | "VIEWED"
    | "REPLIED"
    | "BLOCKED"
    | "REPORTED"
    | "REFUNDED"
    | "EXPIRED"
    | "FAILED";
  credit_source: "FREE" | "PURCHASED" | "NONE";
  credit_cost: number;
  access_expires_at?: string;
  delivered_at?: string;
  viewed_at?: string;
}

export interface ModerationDecision {
  feedback_id?: string;
  conversation_message_id?: string;
  model: string;
  policy_version: string;
  classification: string;
  risk_level: "GREEN" | "YELLOW" | "ORANGE" | "RED";
  decision: "ALLOW" | "REWRITE" | "HUMAN_REVIEW" | "REJECT";
  reason_codes: string[];
  removed_claims?: string[];
  refined_text?: string;
}

export interface PhoneVerification {
  user_id: string;
  phone_hash: string;
  phone_ciphertext: string;
  phone_iv: string;
  code_hash: string;
  expires_at: string;
  attempts: number;
  status: "PENDING" | "VERIFIED" | "EXPIRED" | "LOCKED";
}

export interface Profile {
  user_id: string;
  nickname: string;
  phone_hash: string;
  phone_last4: string;
  phone_verified: boolean;
  sms_consent_status: "NONE" | "ACTIVE" | "STOPPED";
  sms_consent_at?: string;
  sms_consent_version?: string;
  free_credit_remaining: number;
  purchased_credits: number;
  account_status: "ACTIVE" | "SUSPENDED" | "BANNED";
  risk_score: number;
  trust_level: "NEW" | "VERIFIED" | "TRUSTED" | "RESTRICTED";
}

export interface Purchase {
  user_id: string;
  product_type: "SINGLE_MESSAGE" | "PACK_20";
  subtotal_cents: number;
  tax_cents: number;
  total_cents: number;
  currency: string;
  credits: number;
  processor: string;
  processor_payment_id?: string;
  status: "PENDING" | "PAID" | "FAILED" | "REFUNDED";
}

export interface RecipientBlock {
  recipient_user_id: string;
  blocked_sender_user_id: string;
  reason?: string;
  active: boolean;
}

export interface RecipientIdentity {
  user_id: string;
  phone_hash: string;
  phone_ciphertext: string;
  phone_iv: string;
  phone_last4: string;
  sms_consent_status: "NONE" | "ACTIVE" | "STOPPED";
  consent_source?: "REGISTRATION" | "KEYWORD" | "SETTINGS";
  consent_timestamp?: string;
  consent_version?: string;
  last_sms_at?: string;
  messages_last_24h: number;
}

export interface SMSMessage {
  telnyx_message_id?: string;
  direction: "INBOUND" | "OUTBOUND";
  from_number: string;
  to_number: string;
  body: string;
  message_type?: string;
  feedback_id?: string;
  status: string;
  carrier_status?: string;
  failure_reason?: string;
}

export interface WebhookEvent {
  provider: "TELNYX" | "STRIPE";
  event_id: string;
  event_type: string;
  processed: boolean;
  processed_at?: string;
  payload_hash?: string;
  error?: string;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "AbuseReport": AbuseReport;
    "Conversation": Conversation;
    "ConversationMessage": ConversationMessage;
    "CreditTransaction": CreditTransaction;
    "FeedbackAccessToken": FeedbackAccessToken;
    "FeedbackMessage": FeedbackMessage;
    "ModerationDecision": ModerationDecision;
    "PhoneVerification": PhoneVerification;
    "Profile": Profile;
    "Purchase": Purchase;
    "RecipientBlock": RecipientBlock;
    "RecipientIdentity": RecipientIdentity;
    "SMSMessage": SMSMessage;
    "WebhookEvent": WebhookEvent;
  }
  
  interface FunctionNameRegistry {
    "app-api": true;
    "cleanup-expired": true;
    "telnyx-webhook": true;
    "stripe-webhook": true;
    "app-api/base44/functions/app-api": true;
    "telnyx-webhook/base44/functions/telnyx-webhook": true;
    "stripe-webhook/base44/functions/stripe-webhook": true;
    "cleanup-expired/base44/functions/cleanup-expired": true;
  }
  
  interface AgentNameRegistry {
    "feedback_moderator": true;
  }
}